name: Docker CI

on:
  schedule:
    - cron: '0 1 1 * *' # 매월 1일 10:00 (UTC 01:00)
  push:
    branches:
      - 'master'
    paths:
      - 'Dockerfile'
      - 'docker-node.env'
      - 'src/**'
      - 'version.txt'
  pull_request:

jobs:
  edge:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v2.4.0
        with:
          push: github.event_name != 'pull_request'
          tags: |
            divlook/node:edge
            ghcr.io/divlook/node:edge

  latest:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      -
        name: Sleep for 60 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '60s'
      -
        name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      -
        name: Get Latest Tag
        id: tag
        run: |
          TAG=$(git describe --tags $(git rev-list --tags --max-count=1) || echo 'master')
          echo "::set-output name=latest::$TAG"
          git checkout $TAG
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          push: true
          tags: |
            divlook/node:latest
            divlook/node:${{ steps.tag.outputs.latest }}
            ghcr.io/divlook/node:latest
            ghcr.io/divlook/node:${{ steps.tag.outputs.latest }}
