name: Docker CI

on:
  schedule:
    - cron: '0 1 1 * *' # 매월 1일 10:00 (UTC 01:00)
  push:
    branches:
      - 'master'
    tags:
      - 'v*.*.*'
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - '.gitignore'
  pull_request:

jobs:
  release:
    if: github.event_name != 'schedule'
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: |
            divlook/node
            ghcr.io/divlook/node
          tag-edge: true
          tag-semver: |
            v{{major}}.{{minor}}.{{patch}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

  latest:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Get Latest Tag
        id: tag
        run: |
          TAG=$(git describe --tags $(git rev-list --tags --max-count=1) || echo 'master')
          echo "::set-output name=latest::$TAG"
          git checkout $TAG
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            divlook/node:latest
            divlook/node:${{ steps.tag.outputs.latest }}
            ghcr.io/divlook/node:latest
            ghcr.io/divlook/node:${{ steps.tag.outputs.latest }}
