name: Release Please

on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          package-name: docker-node

      - uses: actions/checkout@v2

      - name: tag major and patch versions
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config user.name uihyeon.cha
          git config user.email uihyeon.cha@gmail.com
          git tag -a v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}".${{ steps.release.outputs.patch }}"
          git push origin v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}".${{ steps.release.outputs.patch }}"
